#goal
c2_ros_msgs/Trajectory mission_traj
bool isOverwrite 							#overwrite the previous goal if true, otherwise, appended to the last goal
---

#result
bool isSucceeded

---

#feedback
#percentage (0-100%)
uint8 progress 