{
######### Common ##########




######## Captain ##########

default_desired_speed   :  5,
default_m_pt_radius     :  5,
mission_file_location   :  /home/odroid/Missions/mission.txt,  
#home location, lat lon takes precedence
#home_lat      :  39.4503303,
#home_lon      : -76.5518334,
homeX          : 207,
homeY          : 77,

######## Params for SafetyOfficer agent ##########
opArea_vertices : 4,
opArea_vertex_1 : 150/150,
opArea_vertex_2 : 150/-150,
opArea_vertex_3 : -150/-150,
opArea_vertex_4 : -150/150,


######## Vehicle_Simulated ###############

turnRate    : 30, #deg per second
thrustScale : 1,  #scale of thrust to speed conversion

#ocean current simulation 
currentSpeed    : 0, #meter per second
currentYaw      : 0, #radian

startX          : 0,
startY          : 0,


######## Params for lawnmow agent ##########
lm_xlength      : 100,         #meters
lm_ylength      : 100,         #meters
lm_mowewidth    : 20,         #meters
lm_mowebearing  : 90           #deg




}
